## Inicializando o aprendizado de maquina!

In [4]:
acm = 0
for i in range(10):
    acm += 1
print(acm)

10


In [3]:
print("Meu Primeiro Machine Learning")

Meu Primeiro Machine Learning


# Importação de bibliotecas

In [1]:
# Importação das bibliotecas
import pandas as pd #Para a manipulação de DataFrames
import numpy as np # Cálculo algébricos
import matplotlib.pyplot as plt #Visualização dos dados
from sklearn import datasets as sck #mineração de dados

# Regressao Linear

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_boston

In [40]:
df = load_boston()
X = df.data
y = df.target

In [41]:
X #dados carregados 1

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [42]:
y #dados carregados 2

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [43]:
df #tabela de dados completa

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [44]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [45]:
classifier = LinearRegression()
classifier.fit(X_train, y_train)
predictions = classifier.predict(X_test)

In [46]:
print(predictions)

[27.34659273 29.4981509  20.38715541 36.99193464 20.23735746 30.09078491
 16.23758292 36.58642353 20.5097508  30.17717257 17.96181166 19.9604107
  3.27237236 13.76521721 27.0957457  25.65850482 22.33375059 18.55831643
 14.72089285 13.96801036 24.09945693 26.60569092 18.99467606 24.64290472
 23.731984   20.38916233 20.05209537 30.87008043 30.84043399  8.19530802
 23.38376624 13.41997484 20.29619865 20.48974851 17.82616821 28.65154072
 14.49089796 43.52937694 16.28988259 25.24435978 17.60969417 11.43028863
  5.90872906 13.5826816  15.14919732 20.17512189 25.15702036 30.63185136
 24.70842663 33.26448396 17.4676472  34.74081138 18.20067612 24.12179767
 25.89697104 36.07512074 20.24135223 20.65435736 18.74896952 18.18488721
 21.54364998 23.0811578  30.59613856  5.81608507 21.75050764 28.56859471
 22.19743886 22.41905345 20.51916484  3.33663765 14.45491249 22.14349675
 32.73986169 31.49835341 33.30612184 18.76786973 22.35126966 21.47057405
 16.43488608 19.90504851 19.12607516 26.25084502 20.

In [47]:
from math import sqrt
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [48]:
print("RMSE: ", sqrt(mean_squared_error(y_test, predictions)))
print("MAE: ", mean_absolute_error(y_test, predictions))

RMSE:  4.496274661609289
MAE:  3.0987566649454656


# Regressao Logistica

In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [52]:
df = load_iris()
X = df.data
y = df.target

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [54]:
classifier = LogisticRegression()
classifier.fit(X_train, y_train)
predictions = classifier.predict(X_test)

/home/ocean/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/ocean/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [55]:
print(predictions)

[1 1 0 1 0 2 2 0 2 1 1 2 0 2 0 2 2 1 0 2 2 0 0 1 1 0 2 0 0 2]


In [56]:
print(df.target_names)

['setosa' 'versicolor' 'virginica']


In [57]:
d = {0: 'setosa', 1: 'versicolor', 2: 'virginica'}

In [58]:
print(list(map(lambda x: d[x], predictions)))

['versicolor', 'versicolor', 'setosa', 'versicolor', 'setosa', 'virginica', 'virginica', 'setosa', 'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa', 'virginica', 'setosa', 'virginica', 'virginica', 'versicolor', 'setosa', 'virginica', 'virginica', 'setosa', 'setosa', 'versicolor', 'versicolor', 'setosa', 'virginica', 'setosa', 'setosa', 'virginica']


In [59]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predictions)

array([[11,  0,  0],
       [ 0,  8,  1],
       [ 0,  0, 10]])

# naive bays

In [ ]:
import pandas as pd

from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [10]:
df = pd.read_csv('Iris.csv')

In [11]:
X = df.iloc[:, :-1].values

In [12]:
y = df.iloc[:, -1].values

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [14]:
classifier = GaussianNB()

NameError: name 'GaussianNB' is not defined

In [15]:
classifier.fit(X_train, y_train)

NameError: name 'classifier' is not defined

In [40]:
predictions = classifier.predict(X_test)

In [41]:
print(predictions)

[2 0 2 0 1 2 1 1 2 0 1 1 1 2 0 2 2 1 2 1 1 0 2 0 2 1 2 0 0 1]


# Arvore de Decisao

In [1]:
import pandas as pd

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('titanic.csv')

In [3]:
df.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [4]:
X = df.iloc[:, 2:]

In [5]:
y = df.iloc[:, 1]

In [6]:
X = X.drop(['Name', 'Cabin', 'Ticket', 'Embarked'], axis = 1)

In [7]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
Pclass    891 non-null int64
Sex       891 non-null object
Age       714 non-null float64
SibSp     891 non-null int64
Parch     891 non-null int64
Fare      891 non-null float64
dtypes: float64(2), int64(3), object(1)
memory usage: 41.8+ KB


In [8]:
X.Sex = LabelEncoder().fit_transform(X.Sex)

In [9]:
X = X.fillna(X.Age.mean())

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [17]:
classifier = DecisionTreeClassifier()

In [18]:
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [19]:
predictions = classifier.predict(X_test)

In [20]:
print(predictions)

['Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica']


# KNN

In [21]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [22]:
df = pd.read_csv('zoo.csv')

In [23]:
df.head(10)

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   
5     buffalo     1         0     0     1         0        0         0   
6        calf     1         0     0     1         0        0         0   
7        carp     0         0     1     0         0        1         0   
8     catfish     0         0     1     0         0        1         1   
9        cavy     1         0     0     1         0        0         0   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   
5        1         1         1         0     0     4     1         0        1   
6        1         1         1         0     0     4     1         1        1   
7        1         1         0         0     1     0     1         1        0   
8        1         1         0         0     1     0     1         0        0   
9        1         1         1         0     0     4     0         1        0   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1  
5           1  
6           1  
7           4  
8           4  
9           1

In [24]:
X = df.iloc[:, 1:-1]
y = df.iloc[:, -1]

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [26]:
classifier = KNeighborsClassifier()

In [27]:
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [28]:
predictions = classifier.predict(X_test)

In [29]:
print(predictions)

[2 2 6 2 5 1 7 4 1 4 1 2 1 1 1 2 2 6 6 1 1]


In [30]:
pd.DataFrame({'True Label': y_test,
             'Predicted Label': predictions,
            'Correct': y_test == predictions})

True Label  Predicted Label  Correct
87            2                2     True
83            2                2     True
88            6                6     True
57            2                2     True
89            5                5     True
65            1                1     True
72            7                7     True
76            3                4    False
10            1                1     True
62            3                4    False
28            1                1     True
58            2                2     True
75            1                1     True
84            1                1     True
36            1                1     True
16            2                2     True
100           2                2     True
97            6                6     True
42            6                6     True
5             1                1     True
3             1                1     True

In [31]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predictions)

array([[8, 0, 0, 0, 0, 0, 0],
       [0, 6, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 1]])

# SVM

In [32]:
import pandas as pd

from sklearn.svm import SVC
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [33]:
df = load_iris()

In [34]:
X = df.data
y = df.target

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [36]:
classifier = SVC()
classifier.fit(X_train, y_train)

/home/ocean/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [37]:
predictions = classifier.predict(X_test)

In [38]:
print(predictions)

[2 0 2 0 1 2 1 1 2 0 1 1 1 2 0 2 2 1 2 1 1 0 2 0 2 1 2 0 0 1]


In [39]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predictions)

array([[ 8,  0,  0],
       [ 0,  9,  0],
       [ 0,  2, 11]])